In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()

Saving SalaryData_Train.csv.crdownload to SalaryData_Train.csv (1).crdownload

In [4]:
Train=pd.read_csv("SalaryData_Train.csv (1).crdownload")

In [5]:
from google.colab import files
uploaded=files.upload()

Saving SalaryData_Train.csv.crdownload to SalaryData_Train.csv (2).crdownload

In [6]:
Test=pd.read_csv("/content/SalaryData_Test.csv.crdownload")

In [7]:
Train.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K

In [8]:
Test.shape

(3430, 14)

In [9]:
Train.shape

(3501, 14)

In [10]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3501 entries, 0 to 3500
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            3501 non-null   int64
 1   workclass      3501 non-null   object
 2   education      3500 non-null   object
 3   educationno    3500 non-null   float64
 4   maritalstatus  3500 non-null   object
 5   occupation     3500 non-null   object
 6   relationship   3500 non-null   object
 7   race           3500 non-null   object
 8   sex            3500 non-null   object
 9   capitalgain    3500 non-null   float64
 10  capitalloss    3500 non-null   float64
 11  hoursperweek   3500 non-null   float64
 12  native         3500 non-null   object
 13  Salary         3500 non-null   object
dtypes: float64(4), int64(1), object(9)
memory usage: 383.0+ KB

In [11]:
Test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3430 entries, 0 to 3429
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            3430 non-null   int64
 1   workclass      3430 non-null   object
 2   education      3430 non-null   object
 3   educationno    3430 non-null   int64
 4   maritalstatus  3429 non-null   object
 5   occupation     3429 non-null   object
 6   relationship   3429 non-null   object
 7   race           3429 non-null   object
 8   sex            3429 non-null   object
 9   capitalgain    3429 non-null   float64
 10  capitalloss    3429 non-null   float64
 11  hoursperweek   3429 non-null   float64
 12  native         3429 non-null   object
 13  Salary         3429 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 375.3+ KB

In [12]:
Train.describe()

               age  educationno   capitalgain  capitalloss  hoursperweek
count  3501.000000  3500.000000   3500.000000  3500.000000   3500.000000
mean     38.727221    10.151714   1051.330000    97.345429     41.226857
std      13.074058     2.542153   7142.596411   420.910754     11.529500
min      17.000000     1.000000      0.000000     0.000000      1.000000
25%      28.000000     9.000000      0.000000     0.000000     40.000000
50%      38.000000    10.000000      0.000000     0.000000     40.000000
75%      47.000000    13.000000      0.000000     0.000000     45.000000
max      90.000000    16.000000  99999.000000  2547.000000     99.000000

In [13]:
Test.describe()

               age  educationno   capitalgain  capitalloss  hoursperweek
count  3430.000000  3430.000000   3429.000000  3429.000000   3429.000000
mean     38.462391    10.081633   1240.237387    93.156897     40.930592
std      13.358579     2.576853   8193.162340   416.219997     12.227013
min      17.000000     1.000000      0.000000     0.000000      1.000000
25%      28.000000     9.000000      0.000000     0.000000     40.000000
50%      37.000000    10.000000      0.000000     0.000000     40.000000
75%      47.000000    13.000000      0.000000     0.000000     45.000000
max      90.000000    16.000000  99999.000000  3175.000000     99.000000

In [14]:
Test.isin(['?']).sum(axis=0)

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [15]:
Train.isin(['?']).sum(axis=0)

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [16]:
Train.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K

In [17]:
# find categorical variables

categorical = [var for var in Train.columns if Train[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :\n\n', categorical)

There are 9 categorical variables

The categorical variables are :

 ['workclass', 'education', 'maritalstatus', 'occupation', 'relationship', 'race', 'sex', 'native', 'Salary']

In [18]:
Train[categorical].head()

,workclass,education,maritalstatus,occupation,relationship,race,sex,native,Salary
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K

In [19]:
#There are 9 categorical variables.

#The categorical variables are given by workclass, education, maritalstatus, occupation, relationship, race, sex, native and Salary.

#Salary is the target variable.

In [20]:
Train[categorical].isnull().sum()
#no null values

workclass        0
education        1
maritalstatus    1
occupation       1
relationship     1
race             1
sex              1
native           1
Salary           1
dtype: int64

In [21]:
#value counts for all the columns

for var in categorical:
  print(Train[var].value_counts())

 Private             2568
 Self-emp-not-inc     297
 Local-gov            251
 State-gov            145
 Self-emp-inc         137
 Federal-gov          101
 Without-pay            1
 L                      1
Name: workclass, dtype: int64
 HS-grad         1142
 Some-college     758
 Bachelors        618
 Masters          191
 Assoc-voc        148
 11th             136
 Assoc-acdm       108
 10th              96
 Prof-school       66
 7th-8th           62
 9th               53
 Doctorate         39
 5th-6th           33
 12th              32
 1st-4th           13
 Preschool          5
Name: education, dtype: int64
 Married-civ-spouse       1642
 Never-married            1111
 Divorced                  487
 Separated                 106
 Widowed                   106
 Married-spouse-absent      44
 Married-AF-spouse           4
Name: maritalstatus, dtype: int64
 Exec-managerial      468
 Prof-specialty       453
 Sales                451
 Craft-repair         447
 Adm-clerical         430
 Other-service        371
 Machine-op-inspct    242
 Transport-moving     186
 Handlers-cleaners    141
 Farming-fishing      113
 Tech-support         110
 Protective-serv       71
 Priv-house-serv       15
 Armed-Forces           2
Name: occupation, dtype: int64
 Husband           1447
 Not-in-family      907
 Own-child          485
 Unmarried          383
 Wife               178
 Other-relative     100
Name: relationship, dtype: int64
 White                 3002
 Black                  354
 Asian-Pac-Islander      91
 Amer-Indian-Eskimo      33
 Other                   20
Name: race, dtype: int64
 Male      2385
 Female    1115
Name: sex, dtype: int64
 United-States                 3197
 Mexico                          80
 Germany                         15
 Canada                          15
 Philippines                     14
 England                         13
 Cuba                            13
 Puerto-Rico                     11
 China                           10
 Dominican-Republic              10
 Italy                            9
 Japan                            9
 India                            9
 El-Salvador                      9
 Poland                           8
 Iran                             8
 Guatemala                        7
 Jamaica                          7
 Taiwan                           6
 Portugal                         6
 Greece                           5
 Nicaragua                        4
 South                            4
 Haiti                            4
 Columbia                         4
 Trinadad&Tobago                  3
 Vietnam                          3
 France                           2
 Thailand                         2
 Cambodia                         2
 Peru                             2
 Honduras                         2
 Laos                             1
 Ecuador                          1
 Yugoslavia                       1
 Outlying-US(Guam-USVI-etc)       1
 Scotland                         1
 Hong                             1
 Ireland                          1
Name: native, dtype: int64
 <=50K    2601
 >50K      899
Name: Salary, dtype: int64

In [22]:
Train.workclass.unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' Self-emp-inc', ' Without-pay', ' L'], dtype=object)

In [23]:
# check for cardinality in categorical variables

for var in categorical:

    print(var, ' contains ', len(Train[var].unique()), ' labels')

workclass  contains  8  labels
education  contains  17  labels
maritalstatus  contains  8  labels
occupation  contains  15  labels
relationship  contains  7  labels
race  contains  6  labels
sex  contains  3  labels
native  contains  40  labels
Salary  contains  3  labels

In [24]:
numerical = [var for var in Train.columns if Train[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

There are 5 numerical variables

The numerical variables are : ['age', 'educationno', 'capitalgain', 'capitalloss', 'hoursperweek']

In [25]:
# view the numerical variables

Train[numerical].head()

   age  educationno  capitalgain  capitalloss  hoursperweek
0   39         13.0       2174.0          0.0          40.0
1   50         13.0          0.0          0.0          13.0
2   38          9.0          0.0          0.0          40.0
3   53          7.0          0.0          0.0          40.0
4   28         13.0          0.0          0.0          40.0

In [26]:
#There are 5 numerical variables.

#These are given by age, educationno, capitalgain, capitalloss and hoursperweek. All of the numerical variables are of discrete data type.

In [27]:
# check missing values in numerical variables

Train[numerical].isnull().sum()

age             0
educationno     1
capitalgain     1
capitalloss     1
hoursperweek    1
dtype: int64

In [28]:
#split into X and Y

X = Train.drop(['Salary'], axis=1)

y = Train['Salary']

In [29]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [30]:
X_train.shape, X_test.shape

((2450, 13), (1051, 13))

In [31]:
X_train.dtypes

age                int64
workclass         object
education         object
educationno      float64
maritalstatus     object
occupation        object
relationship      object
race              object
sex               object
capitalgain      float64
capitalloss      float64
hoursperweek     float64
native            object
dtype: object

In [32]:
X_test.dtypes

age                int64
workclass         object
education         object
educationno      float64
maritalstatus     object
occupation        object
relationship      object
race              object
sex               object
capitalgain      float64
capitalloss      float64
hoursperweek     float64
native            object
dtype: object

In [33]:
X_train.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
dtype: int64

In [34]:
X_test.isnull().sum()

age              0
workclass        0
education        1
educationno      1
maritalstatus    1
occupation       1
relationship     1
race             1
sex              1
capitalgain      1
capitalloss      1
hoursperweek     1
native           1
dtype: int64

In [35]:
#Encode categorical variables

In [36]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.2-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.2

In [37]:
import category_encoders as ce

In [38]:
encoder = ce.OneHotEncoder(cols=['workclass', 'education', 'maritalstatus', 'occupation', 'relationship',
                                 'race', 'sex', 'native'])

X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [39]:
X_train.head()

,age,workclass_1,workclass_2,workclass_3,workclass_4,workclass_5,workclass_6,education_1,education_2,education_3,...,native_30,native_31,native_32,native_33,native_34,native_35,native_36,native_37,native_38,native_39
820,28,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
886,32,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1288,31,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
414,44,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2285,74,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [40]:
X_train.shape

(2450, 100)

In [41]:
X_test.head()

,age,workclass_1,workclass_2,workclass_3,workclass_4,workclass_5,workclass_6,education_1,education_2,education_3,...,native_30,native_31,native_32,native_33,native_34,native_35,native_36,native_37,native_38,native_39
1269,25,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
118,31,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2810,40,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2621,27,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1535,51,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
X_test.shape

(1051, 100)

In [43]:
#let us scale our data

In [44]:
cols = X_train.columns

In [45]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [46]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [47]:
X_test = pd.DataFrame(X_test, columns=[cols])

In [48]:
X_train.head()

,age,workclass_1,workclass_2,workclass_3,workclass_4,workclass_5,workclass_6,education_1,education_2,education_3,...,native_30,native_31,native_32,native_33,native_34,native_35,native_36,native_37,native_38,native_39
0,-0.473684,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-0.263158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-0.315789,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.368421,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.947368,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
# train a Gaussian Naive Bayes classifier on the training set


from sklearn.naive_bayes import GaussianNB


# instantiate the model
gnb = GaussianNB()


# fit the model
gnb.fit(X_train, y_train)

GaussianNB()

In [52]:
#we got 79% of accuracy

In [ ]:
#We can see the training and testing data accuracy is almost same.

In [ ]:
#Confusion matrix

In [ ]:
#True Positives(TP) =  5422
#True Negatives(TN) =  1813
#False Positives(FP) =  1376
#False Negatives(FN) =  438

In [55]:
#We got the accuracy of 80% for this model.
#GaussianNB → When you have continuous features. CategoricalNB →When you have categorical data. MultinomialNB → Applied to text data.